# Generated by Django 4.0 on 2022-04-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spy',
            old_name='profile',
            new_name='organiser',
        ),
    ]
