# Generated by Django 4.0 on 2022-04-01 18:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0002_alter_lead_options_lead_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='text_area',
            field=models.TextField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
