# Generated by Django 4.0 on 2022-04-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0003_user_is_agent_user_is_organiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_organiser',
            new_name='is_organised',
        ),
    ]
