# Generated by Django 4.0 on 2022-04-02 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0003_lead_text_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='text_area',
        ),
    ]
