# Generated by Django 4.0 on 2022-04-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0004_rename_is_organiser_user_is_organised'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crmblog.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='spy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crmblog.spy'),
        ),
    ]
