# Generated by Django 4.0.4 on 2022-04-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmblog', '0006_category_lead_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Main Category Model'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
    ]
